<div class="page-header">
					<div class="brand"><a href="./">I DEYVEX</div>
					<div class="other-links">
					 	<div class="link-container"><a class= "link primary" href="post/">I dey vex ...</a></div>
						<div class="link-container"><a class= "link" href="about/">About</a></div>
						<div class="link-container"><a class= "link" href="trending/">Trending</a></div>
						<div class="link-container"><a class= "link" href="contact/">Contact</a></div>
					</div>
				</div>