<div class="error alert"></div>
<div class="success alert"></div>
<div class="info alert"></div>
<div class="page-header">
					<div class="brand"><a class="dyna-link" href="http://localhost/idv/">I DEYVEX</div>
					<div class="other-links">
					 	<div class="link-container"><a class= "link primary new-post dyna-link" href="http://localhost/idv/p/post">Post</a></div>
						<div class="link-container"><a class= "link" href="//localhost/idv/p/about">About</a></div>
						<div class="link-container"><a class= "link" href="//localhost/idv/p/trending">Trending</a></div>
						<div class="link-container"><a class= "link" href="//localhost/idv/p/contact">Contact</a></div>
					</div>
				</div>