<title>IDEYVEX | Rant anonymously</title>
<link rel="stylesheet" type="text/css" href="//localhost/idv/assets/css/style.css">
<link rel="stylesheet" type="text/css" href="//localhost/idv/assets/tooltipster/css/tooltipster.bundle.min.css" />
<script type="text/javascript" src="//localhost/idv/assets/js/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="//localhost/idv/assets/js/date.js"></script>