<div class="vexation-content">
	<a href="vexation-555">I dey vex cos the dude I dated for 9years suddenly left without looking back. It sucks to remain faithful!</a>
</div>
<div class="vexation-footer">
	<a class="actionable" href="#novex"><span class="novex emotion">novex 6</span></a>
	<a class="actionable" href="#cheya"><span class="cheya emotion">cheya 1</span></a>
	<a class="actionable" href="#abegi"><span class="abegi emotion">abegi 7</span></a>
	<a class="actionable" href="#comment"><span class="comment emotion">comment 33</span></a>
	<span class="inside"><a class="link" href="vexation-555">12.11.16 02:15pm →</a></span>
</div>